version: '3.8'
services:
  gf-controle-acesso-api:
    container_name: gf-controle-acesso-api
    image: victorb96/gf-controle-acesso:latest
    restart: always
    environment:
      - DB_HOST=tediously-entranced-conger.data-1.use1.tembo.io
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PWD=${POSTGRES_PASSWORD}
      - JWT_CONTROLE_ACESSO_KEY=${JWT_CONTROLE_ACESSO_KEY}
    networks:
      - gf-network
    ports:
      - 8080:8080

  gf-app:
    container_name: gf-app
    build:
      context: ./../
    environment:
      - NODE_ENV=production
      - URL_API=http://localhost:8080
    depends_on:
      - gf-controle-acesso-api
    ports:
      - 10000:80
    networks:
      - gf-network

networks:
  gf-network:
    driver: bridge
